api.go
api_test.go
cmd/forseti/main.go
data.go
fixtures/vehicles.json
loader.go
loader_test.go
readme.md
type.go
type_test.go
utils.go

Concerned ticket: https://jira.kisio.org/browse/NAVP-1704
* API /free_floatings added
* Work in pregress.
* More tests to come.
Parameters:
* coord mandatory (coord=2.37715%3B48.846781)
* distance (default value=500 m)
* count (default value = 10)
* type[] (possible values=BIKE, SCOOTER, MOTORSCOOTER, STATION, CAR, OTHER) 
Response json:
```{
"free_floatings": [
{
"public_id": "381WRY",
"provider_name": "Tier",
"id": "dGllcjpTQ09PVEVSOjk5Zjk1OGVkLTExY2EtNGY1NC04YWYxLTk0MDZjNTlkMWQwMA==",
"type": "SCOOTER",
"coord": {
"lat": 48.847232,
"lon": 2.377601
},
"propulsion": "ELECTRIC",
"battery": 40,
"attributes": [
"ELECTRIC"
]
},
{
"public_id": "977WSK",
"provider_name": "Tier",
"id": "dGllcjpTQ09PVEVSOmFhMmI1OGFkLWE3YjAtNDg2OC05NTFjLTFhMzY3MDk5NDg3Ng==",
"type": "SCOOTER",
"coord": {
"lat": …
```

Add free floating

---

api_test.go
type.go
utils.go

Concerned ticket: https://jira.kisio.org/browse/NAVP-1704

Add distance in free_floating and map replaced by array

---

.github/workflows/release.yml

Like: [Navitia](https://github.com/CanalTP/navitia/pull/3386)

[CI] fill releases field with release ga job

---

api.go
api_test.go
cmd/forseti/main.go
go.mod
go.sum
internal/freefloatings/api.go
internal/freefloatings/context.go
internal/freefloatings/free_floatings.go
internal/freefloatings/free_floatings_test.go
internal/freefloatings/prometheus.go
loader.go
loader_test.go
type.go
type_test.go

In the same way of equipements (https://github.com/CanalTP/forseti/pull/20), I isolated the free floating code.
```
forseti
|
|---cmd
|     |---main.go
|---internal
|     |---freefloatings
|     |    |---context.go
|     |    |---api.go
|     |    |---freefloatings.go
|     |    |---free_floatings_test.go
|     |    |---prometheus.go
|     | ...
|     | ...
|---Dockerfile
|---Makefile
|...
```

Free Floating: Reshape Api

---

readme.md

Fix: Readme link for vehicule_occupancies

---

Dockerfile
cmd/forseti/main.go
fixtures/extraction_courses0.csv
fixtures/mapping_stops0.csv
internal/departures/departures.go
internal/equipments/equipments.go
internal/freefloatings/free_floatings.go
internal/parkings/parkings.go
internal/utils/utils.go
internal/utils/utils_test.go
internal/vehicleoccupancies/context.go
internal/vehicleoccupancies/vehicleoccupancies.go
internal/vehicleoccupancies/vehicleoccupancies_test.go

Added http error handling: vehicule_occupancies and free_floating.
Changed the declaration on single line for enviroment variables  in the Dockerfile

http error handling for external services

---

internal/vehicleoccupancies/context.go
internal/vehicleoccupancies/contextGtfsRt.go
internal/vehicleoccupancies/factory.go
internal/vehicleoccupancies/navitia.go
internal/vehicleoccupancies/vehicleoccupancies_test.go

Creation of the structure to integrate a GTFS-RT flow in the Vehicle_occupancies API.
- declaration of the vehicleOccupancies interface
- creation of the factory
- declaration of structs and methods (no implemented)

Add structure gtfs realtime in Vehicle_occupancies

---

internal/freefloatings/context.go
internal/freefloatings/free_floatings_test.go

Concerned ticket: https://jira.kisio.org/browse/NAVITIAII-3429

Keep all vehicles within the distance and truncate at last

---

cmd/forseti/main.go
internal/vehiclelocations/readme.md
internal/vehicleoccupancies/contextGtfsRt.go
internal/vehicleoccupancies/contextOditi.go
internal/vehicleoccupancies/factory.go

- added config parameters for clean list VO et VJ
- used parameters in api (gtfs-rt)

added and used new config parameters for gtfs-rt connector

---

internal/freefloatings/api.go
internal/freefloatings/context.go
internal/freefloatings/free_floatings_test.go
internal/utils/pagination.go
internal/utils/utils_test.go

Added possibility to get paginate for all connector.
Added paginate for freefloatings

Pagination forseti

---

internal/vehicleoccupancies_v2/context.go
internal/vehicleoccupancies_v2/contextGtfsRt.go
internal/vehicleoccupancies_v2/contextGtfsRt_test.go
internal/vehicleoccupancies_v2/readme.md

- Add readme for this new version
- updated clean vehicle occupancy for datemine more than cleanVP parameter

Vehicle occupancy v2

---

api/api_test.go
cmd/forseti/main.go
internal/freefloatings/context.go
internal/freefloatings/fluctuo/fluctuo.go
internal/freefloatings/fluctuo/fluctuo_test.go

- added launch parameter "free-floatings-type"
- created package fluctuo
- moved business methods into fluctuo package

Reshape current free-floating to fluctuo connector

---

internal/vehiclepositions/api.go
internal/vehiclepositions/api_test.go
internal/vehiclepositions/contextGtfsRt_test.go
internal/vehiclepositions/readme.md
internal/vehiclepositions/vehiclepositions.go

Concerned ticket: https://jira.kisio.org/browse/NAVP-1982
replaces: https://github.com/hove-io/forseti/pull/83/

Adding coord and distance parameters in vehicle_positions api

---

internal/departures/data.go
internal/departures/sytralrt/sytralrt.go
internal/departures/sytralrt/sytraltr_test.go

Continue the refactocting of the connector `sytralrt` of the API `departures`

sytralrt: Continue the refactoring of the connector

---

internal/departures/rennes/rennes.go
internal/departures/rennes/vehiclepositions/vehiclepositions_csv.go
internal/departures/rennes/vehiclepositions/vehiclepositions_json.go
internal/vehiclepositions/contextrennes.go
internal/vehiclepositions/navitia.go

No management of the Navitia parameter UTC current datetime

[VehiclePositions][Rennes] Update management of the vehicle states + no navitia `_current_datetime`

---

api/api.go
go.mod
go.sum
internal/vehiclepositions/api.go
internal/vehiclepositions/contextrennes.go

- Update the management the the parameters `vehicle_journey_code[]` for the connector `rennes`
- Update log message of the gin engine

[VehiclePosition] Patch the connector `rennes` + Update log message of the gin engine

---

internal/departures/rennes/vehiclepositions/vehiclepositions_csv.go

`HLP` -> the vehicle is in operation and its position is displayed

[VehiclePositions][Rennes] Update for the state `HLP`

---

cmd/forseti/main.go
internal/departures/readme.md
internal/departures/sirism/sirism.go
internal/departures/sirism/sirism_test.go

For the connector `sirism` add a feature that allows the deletion the departures at a given time of the day,
set it up using the option `--departures-service-switch`

[Departures][SIRI-SM] Add daily departures delete

---

internal/departures/sirism/sirism.go

Only GZIP archives are exepected as record

[SIRI-SM] Uncompressed (GZIP) received Kinesis record

---

internal/departures/sirism/sirism.go

Fix bug, locking mutex while XML parsing error

[SIRI-SM] fix bug, locking mutex while XML parsing error

---

api/api.go

Log level Info should not log any call of health check (/status)

Avoid log on health check for level=Info
